//------------------------------------------------------------------------------
//  Tenant.cs
//
//  Implementation of: Tenant (Class) <<ef-entity>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 06-ago-2017 19:29:24
//  Original author: Miguel
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace Tenants.Core.Model
{
    public class Tenant
    {
        public Guid Id { get; set; }

        [Required]
        [MaxLength(250)] // Default string length
        public virtual string Email { get; set; } // Key data ----------

        [Required]
        [MaxLength(250)] // Default string length
        public virtual string Name { get; set; }

        public virtual Byte[] ConcurrencyToken { get; set; }
    }
}