//------------------------------------------------------------------------------
//  BudgetDbContext.cs
//
//  Implementation of: BudgetDbContext (Class) <<dbcontext>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:08
//  Original author: Miguel
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;

namespace Tenants.Data.Configuration
{
    public class TenantsDbContext : DbContext
    {
        public TenantsDbContext(DbContextOptions<TenantsDbContext> options)
            : base(options)
        {
        }

        ///
        /// <param name="modelBuilder"></param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            ConfigureLocalModel(modelBuilder);

            ConfigureExternalModel(modelBuilder);
        }

        ///
        /// <param name="modelBuilder"></param>
        private void ConfigureExternalModel(ModelBuilder modelBuilder)
        {
        }

        ///
        /// <param name="builder"></param>
        private void ConfigureLocalModel(ModelBuilder builder)
        {
            // Database schema is "Tenants"

            builder.ApplyConfiguration(new TenantConfiguration());
        }
    }
}
