//------------------------------------------------------------------------------
//  TenantConfiguration.cs
//
//  Implementation of: TenantConfiguration (Class) <<entity-configuration>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 06-ago-2017 19:26:07
//  Original author: Miguel
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Tenants.Core.Model;

namespace Tenants.Infrastructure.Data.Configuration
{
    // 6-2. Add TenantConfiguration
    //-----------------------------

    public class TenantConfiguration : IEntityTypeConfiguration<Tenant>
    {
        public void Configure(EntityTypeBuilder<Tenant> builder)
        {
            builder.ToTable("Tenants", schema: "Tenants");

            builder.HasKey(t => t.Id);

            builder.Property(t => t.ConcurrencyToken)
                .IsRowVersion();

            // Indexes

            builder.HasIndex(t => t.Email)
                .IsUnique();
        }
    }
}