// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tenants.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class _1_ManageTenantsFeature : Xunit.IClassFixture<_1_ManageTenantsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "[1] - Manage Tenants.feature"
#line hidden
        
        public _1_ManageTenantsFeature(_1_ManageTenantsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "[1] - Manage Tenants", "    As a service manager\r\n    I need to manage tenants\r\n    To keep control of th" +
                    "e service", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Scenario - 1.1 - Add tenants")]
        [Xunit.TraitAttribute("FeatureTitle", "[1] - Manage Tenants")]
        [Xunit.TraitAttribute("Description", "Scenario - 1.1 - Add tenants")]
        public virtual void Scenario_1_1_AddTenants()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario - 1.1 - Add tenants", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email"});
            table1.AddRow(new string[] {
                        "tenant-a@server.com"});
            table1.AddRow(new string[] {
                        "tenant-b@server.com"});
#line 8
    testRunner.Given("these tenants don\'t exist:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name"});
            table2.AddRow(new string[] {
                        "tenant-a@server.com",
                        "Add Tenant A"});
            table2.AddRow(new string[] {
                        "tenant-b@server.com",
                        "Add Tenant B"});
#line 13
    testRunner.When("I add tenants:", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name"});
            table3.AddRow(new string[] {
                        "tenant-a@server.com",
                        "Add Tenant A"});
            table3.AddRow(new string[] {
                        "tenant-b@server.com",
                        "Add Tenant B"});
#line 18
    testRunner.Then("when querying for \"Add\" tenants I get these:", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Scenario - 1.2 - Avoid duplicate tenant name")]
        [Xunit.TraitAttribute("FeatureTitle", "[1] - Manage Tenants")]
        [Xunit.TraitAttribute("Description", "Scenario - 1.2 - Avoid duplicate tenant name")]
        [Xunit.InlineDataAttribute("tenant-c@server.com", "Unique Tenant C", new string[0])]
        [Xunit.InlineDataAttribute("tenant-d@server.com", "Unique Tenant D", new string[0])]
        public virtual void Scenario_1_2_AvoidDuplicateTenantName(string email, string name, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scenario - 1.2 - Avoid duplicate tenant name", exampleTags);
#line 23
this.ScenarioSetup(scenarioInfo);
#line 25
    testRunner.Given(string.Format("tenant \"{0}\" does not exist", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 26
    testRunner.When(string.Format("I add tenant \"{0}\", \"{1}\"", email, name), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
    testRunner.Then(string.Format("I can\'t add another tenant \"{0}\", \"{1}\"", email, name), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                _1_ManageTenantsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                _1_ManageTenantsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
